# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20160818_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Cool'), (4, 'Good'), (5, 'Awesome')], default=3),
        ),
    ]
